version: "3"
services:
  rabbitmq:
    container_name: dev-rabbitmq
    hostname: rabbit
    image: my-rabbitmq
    ports:
      - "5672:5672" # rabbitmq port
      - "15672:15672" # management port
  mongodb:
    container_name: dev-mongodb
    hostname: mongodb
    image: mongo
    ports:
      - "27017:27017"
