version: "3"
services:
  rabbitmq:
    container_name: dev-rabbitmq
    hostname: rabbit
    image: rabbitmq:3-management
    ports:
      - "5672:5672" # rabbitmq port
      - "15672:15672" # management port

    
